#!/bin/bash

# Auto-Build Environment Setup - Soul Currency & Economy System
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Vite development server..."
npm run dev &
VITE_PID=$!

# Wait for Vite to start
wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Game:     http://localhost:5173"
echo ""
echo "To stop the server, press Ctrl+C"
echo ""
echo "Backend Requirements:"
echo "  - Supabase project configured (optional for cloud save)"
echo "  - Environment variables in .env:"
echo "    - VITE_SUPABASE_URL"
echo "    - VITE_SUPABASE_ANON_KEY"
echo ""

# Keep script running
wait $VITE_PID
