#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 004

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 004 - Hit Detection & Slicing Feedback"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${YELLOW}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START MAIN GAME SERVICE
# ============================================

echo ""
echo "Starting main game service..."
echo ""

# Navigate to project root (from spec directory)
cd ../../../

# Start Vite dev server in background
npm run dev &
VITE_PID=$!

# Wait for dev server to be ready
wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main Game: http://localhost:5173"
echo ""
echo "Vite PID: $VITE_PID"
echo ""
echo "To stop services:"
echo "  kill $VITE_PID"
echo ""
echo "Ready to implement:"
echo "  - Phase 1: Particle Enhancement (ParticleSystem.ts)"
echo "  - Phase 2: Screen Shake (Monster.ts)"
echo "  - Phase 3: Audio Integration (SlashSystem.ts)"
echo ""
