#!/bin/bash

# Auto-Build Environment Setup for Basic Audio Integration
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo "Checking dependencies..."

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed. Please install Node.js and npm first.${NC}"
    exit 1
fi

echo -e "${GREEN}npm found${NC}"

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# ============================================
# START MAIN SERVICE (Vite Dev Server)
# ============================================

echo ""
echo "Starting Vite dev server..."
echo -e "${YELLOW}Running: npm run dev${NC}"
echo ""

# Start in background
npm run dev &
VITE_PID=$!

# Wait for Vite to be ready
wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main Application: http://localhost:5173"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running and handle cleanup
cleanup() {
    echo ""
    echo "Stopping services..."
    kill $VITE_PID 2>/dev/null || true
    echo "Done."
    exit 0
}

trap cleanup SIGINT SIGTERM

# Wait for user to stop
wait $VITE_PID
