#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Core Slash Mechanics Enhancement

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing npm dependencies...${NC}"
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Vite development server..."

# Start Vite dev server in background
npm run dev &
DEV_SERVER_PID=$!

# Wait for service to be ready
wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Game:  http://localhost:5173"
echo ""
echo "Development Commands:"
echo "  npm run dev      - Start dev server"
echo "  npm run build    - Production build"
echo "  npx tsc --noEmit - Type check"
echo ""
echo "To stop services:"
echo "  kill $DEV_SERVER_PID"
echo ""
echo "========================================"
echo "Core Slash Mechanics Enhancement"
echo "========================================"
echo ""
echo "Features to implement:"
echo "  1. Energy/Stamina System"
echo "  2. Slash Power/Charge Mechanics"
echo "  3. Pattern Recognition (circle, zigzag, straight)"
echo "  4. Enhanced Visual Feedback"
echo "  5. Performance Optimization"
echo ""
echo "Next Steps:"
echo "  - Review implementation_plan.json for subtasks"
echo "  - Start with phase-1-foundation (types & constants)"
echo "  - Test in browser at http://localhost:5173"
echo ""
